# Site Settings
title: Sinhala Wal Katha 2026
description: අලුත්ම සිංහල වල් කතා 2026 - Sinhala Wal Katha සහ Romantic කතා එකතුව
url: "https://wal-katha.github.io"
baseurl: "/sinhala-wal-katha-2026"

# Language & Timezone
lang: si
timezone: Asia/Colombo

# Author
author:
  name: Wal Katha
  url: https://wal-katha.github.io/sinhala-wal-katha-2026/

# Exclude files
exclude:
  - README.md
